apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sock-shop

resources:
  - ../sock-shop

images:
  - name: mongo
    newName: mongo
    newTag: "4.4"

patches:
  - path: session-db-patch.yaml
  - path: front-end-replicas.yaml
  - path: front-end-audit-test.yaml
